# Generated by Django 4.2.3 on 2023-07-23 18:22

import apps.Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last_name')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='nickname')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='user address')),
                ('city', models.CharField(blank=True, max_length=250, verbose_name='user city')),
                ('state', models.CharField(blank=True, max_length=250, verbose_name='user state')),
                ('district', models.CharField(blank=True, choices=[('AL', 'Alappuzha'), ('ER', 'Ernakulam'), ('ID', 'Idukki'), ('KN', 'Kannur'), ('KS', 'Kasaragod'), ('KL', 'Kollam'), ('KT', 'Kottayam'), ('KZ', 'Kozhikode'), ('MA', 'Malapuram'), ('PL', 'Palakkad'), ('PT', 'Pathanmthitta'), ('TV', 'Thiruvanathapuram'), ('TS', 'Thirssur'), ('WA', 'Wayanad')], max_length=2, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=250, verbose_name='user zipcode')),
                ('country', models.CharField(blank=True, max_length=250, verbose_name='user country')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='user created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='user updated on')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', apps.Accounts.models.UserManager()),
            ],
        ),
    ]
