# Generated by Django 4.2.3 on 2023-07-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_users_groups_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Date in ( MM/DD/YYYY )'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='games',
            field=models.CharField(choices=[('ALL', 'All Games'), ('Football', 'Football'), ('Cricket', 'Cricket')], default='All', max_length=10),
        ),
    ]
